name: Auto Commit and Push

on:
  schedule:
    - cron: '0 2 * * *' # 매일 오전 11시(KST 기준) 실행
  workflow_dispatch:     # 수동 실행도 가능

jobs:
  auto-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Detect content changes
        run: |
          git add content || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      - name: Commit and push
        run: |
          git commit -m "🌀 auto-update content $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin main
